apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-catalogue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-catalogue
  template:
    metadata:
      labels:
        app: item-catalogue
    spec:
      containers:
        - image: item-catalogue
          name: item-catalogue
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://lallah.db.elephantsql.com:5432/kryfltbl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: kryfltbl
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: item-catalogue
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: item-catalogue