kumuluzee:
  name: item-catalogue-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/Climb
      #connection-url: jdbc:postgresql://climb-db:5432/climb-db
      #connection-url: jdbc:postgresql://localhost:5432/climb-db
      #username: dbuser
      #password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/bukqntkr
      username: bukqntkr
      password: E2SE5Ru_O6OGntAqsOJqi-7QClTANW6d
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/Climb
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                           <Configuration name="comments">
                               <Appenders>
                                   <Console name="console" target="SYSTEM_OUT">
                                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                   </Console>
                                   <Socket name="logstash" host="e2a1c361-f184-4858-a78b-6576703770e0-ls.logit.io"
                                   port="26234" protocol="udp">
                                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                   </Socket>
                               </Appenders>
                               <Loggers>
                                   <!-- Default logger -->
                                   <Root level="all">
                                       <AppenderRef ref="logstash" level="info" />
                                   </Root>
                               </Loggers>
                           </Configuration>'

rest-properties:
  print: hej
  get_broken: true